name: "ci"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: "always"

jobs:
  ci:
    timeout-minutes: 30
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        rust-version: ["1.87.0", "stable"]
    steps:
      - uses: "actions/checkout@v4.2.2"

      - uses: "dtolnay/rust-toolchain@master"
        with:
          toolchain: "${{ matrix.rust-version }}"
          components: "clippy, rustfmt"

      - run: "rustc --version"
      - run: "cargo build --verbose"
      - run: "cargo test --verbose"
      - run: "cargo clippy --verbose -- -D warnings"
      - run: "cargo fmt -- --check"
